// User-facing text in English and Russian (spec 004 FR-003b, research R9). DOM-free: tools import it
// to generate host manifests. `ru` must have exactly the keys of `en` (checked by type and tests).

/** Product name, the same in every language and on every host (searchable: "Heroes 3"). */
export const APP_NAME = 'Heroes 3 Living Map'

export const en = {
  // Settings (labels and option labels)
  setting_spritearchive: 'Sprite archive (H3sprite.lod)',
  setting_dataarchive: 'Data archive (H3bitmap.lod)',
  setting_hotaarchive: 'HotA archive (HotA.lod, for HotA maps)',
  setting_mapfile: 'Map (.h3m)',
  setting_mapsource: 'Map source',
  mapsource_single: 'One map',
  mapsource_folder: 'Folder of maps',
  setting_mapfolder: 'Folder of maps (or a .zip of maps)',
  mapfolder_hint: 'Used when the map source is "Folder of maps"',
  setting_maprotation: 'New map every N minutes (0 = only at start)',
  maprotation_hint: 'Counts only while the wallpaper is visible; used when the map source is "Folder of maps"',
  setting_mapsizemin: 'Smallest map size',
  setting_mapsizemax: 'Largest map size',
  mapsize_s: 'S (36×36)',
  mapsize_m: 'M (72×72)',
  mapsize_l: 'L (108×108)',
  mapsize_xl: 'XL (144×144)',
  mapsize_h: 'H (180×180)',
  mapsize_xh: 'XH (216×216)',
  mapsize_g: 'G (252×252)',
  setting_mapunderground: 'Underground',
  mapunderground_any: 'Any map',
  mapunderground_two: 'Only maps with underground',
  mapunderground_one: 'Only maps without underground',
  action_mapnext: 'Next map now',
  setting_level: 'Level',
  level_random: 'Random',
  level_surface: 'Surface',
  level_underground: 'Underground',
  setting_viewmode: 'Starting view',
  viewmode_random: 'Random place',
  viewmode_centre: 'Map centre',
  viewmode_coords: 'Coordinates',
  setting_viewx: 'Horizontal position, %',
  setting_viewy: 'Vertical position, %',
  viewx_hint: 'Used when the starting view is "Coordinates"',
  setting_viewinterval: 'New random place every N minutes (0 = never)',
  viewinterval_hint: 'Used when the starting view is "Random place"',
  action_viewreroll: 'New random place now',
  setting_scale: 'Scale',
  scale_1: '×1 (pixel for pixel)',
  scale_2: '×2 (as in the original game)',
  scale_3: '×3',
  setting_objects: 'Show objects',
  setting_language: 'Language',
  language_auto: 'Automatic',
  language_en: 'English',
  language_ru: 'Русский',

  // File slots and kinds
  kind_spriteArchive: 'sprite archive (H3sprite.lod)',
  kind_dataArchive: 'data archive (H3bitmap.lod)',
  kind_hotaArchive: 'HotA archive (HotA.lod)',
  kind_map: 'map (.h3m)',
  kind_unknown: 'unknown file',

  // Placeholder and messages ({name} placeholders are filled by format())
  placeholder_title: APP_NAME,
  placeholder_missing: 'Choose in the wallpaper settings: {files}.',
  placeholder_hint: 'The files come from your own Heroes of Might and Magic III Complete installation and never leave this computer.',
  msg_LOADING: 'Loading {file}…',
  msg_FILE_MISSING: '{file} was not found. Choose the file again.',
  msg_FILE_UNREADABLE: '{file} cannot be read: {detail}',
  msg_WRONG_KIND: '{file} is a {found}, not a {expected}.',
  msg_UNKNOWN_FILE: '{file} is not a Heroes III archive or map.',
  msg_UNSUPPORTED_MAP: '{file}: {format} maps are not supported yet.',
  msg_CORRUPT_FILE: '{file} is damaged or unsupported: {detail}',
  msg_DATA_ARCHIVE_MISSING: 'Objects are hidden: choose the data archive (H3bitmap.lod).',
  msg_WEBGL_UNAVAILABLE: 'This system cannot draw the map: WebGL is not available.',
  msg_CONTEXT_LOST: 'Graphics were reset; the map will reappear shortly.',
  msg_CACHE_UNAVAILABLE: 'Local cache is unavailable, so every start decodes the files again.',
  msg_FOLDER_EMPTY: 'No maps (.h3m) found in {file}.',
  msg_FOLDER_FILTERED: 'No map in {file} matches the filters ({detail}).',
  msg_FOLDER_UNREADABLE: 'None of the maps in {file} can be shown: {detail}',
  msg_FOLDER_NEEDS_ZIP: 'This wallpaper app cannot read a folder ({file}): zip the maps into one file and enter the .zip in "Folder of maps".',

  // Browser panel
  panel_title: APP_NAME,
  panel_files: 'Files',
  panel_choose: 'Choose files…',
  panel_drop: 'or drop the archives and a map anywhere on the page (for a HotA map, HotA.lod too)',
  panel_forget: 'Forget files',
  panel_forget_done: 'Files and cached data were removed from this browser.',
  panel_help: 'Where are the files?',
  panel_keys: 'Arrows or drag: scroll · U: level · R: new random place · N: next map · O: objects · H: hide panel',
  panel_hide: 'Hide panel',
  panel_none: 'not chosen',
  panel_choose_folder: 'Choose folder…',
  panel_choose_zip: 'Choose .zip…',
  panel_folder_summary: '{file}: {detail} maps',
  panel_current_map: 'Now: {file}',
  panel_drop_folder: 'Drop a folder of maps or a .zip of maps onto the page, or choose a folder with the button.',

  // Packages and documentation
  package_title: APP_NAME,
  package_description: 'An animated adventure map of Heroes of Might and Magic III (Heroes 3, HoMM3) from your own game files — the Complete edition, and Horn of the Abyss (HotA) for its maps: terrain, objects, heroes and towns, as in the original game. Fan-made, not affiliated with the game publishers. No game files are included.',
  help_files: 'Take H3sprite.lod and H3bitmap.lod from the Data folder of your Heroes III Complete installation and any map (.h3m) from its Maps folder. Maps of Restoration of Erathia, Armageddon\'s Blade, Shadow of Death and Horn of the Abyss are supported. For a HotA map, also choose HotA.lod from the Data folder of your HotA installation; without it a HotA map is missing its terrains and objects.',
  help_privacy: 'The files stay on this computer: they are read locally and never uploaded.',
  help_web: 'Choose the files with the button or drop them onto the page. The browser remembers them until you press "Forget files".',
  help_wallpaper_engine: 'Wallpaper Engine only lets a wallpaper read files inside its own folder, so you must place the files there yourself — without this the wallpaper cannot work. Copy H3sprite.lod and H3bitmap.lod (from the Data folder of your Heroes III Complete installation) and your map (.h3m) into the wallpaper folder, next to index.html; a "game" subfolder is the intended place. The "Sprite archive" and "Data archive" settings default to game\\H3sprite.lod and game\\h3bitmap.lod, so with the standard names only the map needs entering (for example game\\Arrogance.h3m); other names go into the settings the same way. A HotA map also needs HotA.lod copied there and entered in the "HotA archive" setting (for example game\\HotA.lod). For the map source "Folder of maps", Wallpaper Engine cannot list a folder: zip your maps into one file (for example game\\maps.zip, the default) and enter it in "Folder of maps".',
  notice_wallpaper_engine: '<b><i><u>Important:</u></i></b> the wallpaper can only read files inside its own folder, so copy H3sprite.lod, H3bitmap.lod and your map (.h3m) into the wallpaper folder yourself (next to index.html; a "game" subfolder is fine) — otherwise it will not load. The archive settings below already point to game\\H3sprite.lod and game\\h3bitmap.lod; enter your map the same way (game\\YourMap.h3m).<br></br>',
  spacer_wallpaper_engine: '<br></br>',
  help_lively: 'Open "Customise" for the wallpaper in Lively and use "Browse" in the file settings; Lively copies the files into the wallpaper folder. The HotA archive is only needed for HotA maps.',
  help_kde: `Install the plugin, open "Configure Desktop and Wallpaper", pick "${APP_NAME}" and choose the files. The HotA archive is only needed for HotA maps.`,

  // Links and feedback (spec 006): inline Markdown — [text]({url}), **bold**, \`code\` — rendered per
  // surface (plain text in readmes, BBCode on store pages, a link in the browser panel).
  store_links: 'Source code, README and downloads for every host: [GitHub]({repository}) · [releases]({releases}) · [browser version]({pages})',
  store_feedback: 'Suggestions and bug reports go only to [GitHub Issues]({issues}); comments and reviews on store pages are not tracked.',
  store_on_workshop: 'Also on the [Steam Workshop]({workshop}) for Wallpaper Engine.',
  store_on_kde_store: 'Also in the [KDE Store]({kde_store}) for KDE Plasma 6.',
  store_kde_requirements: 'Requires Qt WebEngine for QML, which the store does not install: Fedora — `qt6-qtwebengine`, Debian/Ubuntu — `qml6-module-qtwebengine`, Arch — `qt6-webengine`.',
  kde_webengine_missing: `${APP_NAME} needs Qt WebEngine for QML. Install it and restart Plasma (or log in again): Fedora — qt6-qtwebengine; Debian/Ubuntu — qml6-module-qtwebengine; Arch — qt6-webengine.`,
  panel_version: 'Version {version}',
  panel_report: 'Report a problem',
} as const

export type StringKey = keyof typeof en
export type Language = 'en' | 'ru'

export const ru: Record<StringKey, string> = {
  setting_spritearchive: 'Архив спрайтов (H3sprite.lod)',
  setting_dataarchive: 'Архив данных (H3bitmap.lod)',
  setting_hotaarchive: 'Архив HotA (HotA.lod, для карт HotA)',
  setting_mapfile: 'Карта (.h3m)',
  setting_mapsource: 'Источник карт',
  mapsource_single: 'Одна карта',
  mapsource_folder: 'Папка с картами',
  setting_mapfolder: 'Папка с картами (или .zip с картами)',
  mapfolder_hint: 'Используется, когда источник карт — «Папка с картами»',
  setting_maprotation: 'Новая карта каждые N минут (0 — только при запуске)',
  maprotation_hint: 'Считается только время, пока обои видны; используется, когда источник карт — «Папка с картами»',
  setting_mapsizemin: 'Наименьший размер карты',
  setting_mapsizemax: 'Наибольший размер карты',
  mapsize_s: 'S (36×36)',
  mapsize_m: 'M (72×72)',
  mapsize_l: 'L (108×108)',
  mapsize_xl: 'XL (144×144)',
  mapsize_h: 'H (180×180)',
  mapsize_xh: 'XH (216×216)',
  mapsize_g: 'G (252×252)',
  setting_mapunderground: 'Подземелье',
  mapunderground_any: 'Любые карты',
  mapunderground_two: 'Только карты с подземельем',
  mapunderground_one: 'Только карты без подземелья',
  action_mapnext: 'Следующая карта сейчас',
  setting_level: 'Уровень',
  level_random: 'Случайный',
  level_surface: 'Поверхность',
  level_underground: 'Подземелье',
  setting_viewmode: 'Начальный вид',
  viewmode_random: 'Случайное место',
  viewmode_centre: 'Центр карты',
  viewmode_coords: 'Координаты',
  setting_viewx: 'Положение по горизонтали, %',
  setting_viewy: 'Положение по вертикали, %',
  viewx_hint: 'Используется, когда начальный вид — «Координаты»',
  setting_viewinterval: 'Новое случайное место каждые N минут (0 — никогда)',
  viewinterval_hint: 'Используется, когда начальный вид — «Случайное место»',
  action_viewreroll: 'Новое случайное место сейчас',
  setting_scale: 'Масштаб',
  scale_1: '×1 (пиксель в пиксель)',
  scale_2: '×2 (как в оригинальной игре)',
  scale_3: '×3',
  setting_objects: 'Показывать объекты',
  setting_language: 'Язык',
  language_auto: 'Автоматически',
  language_en: 'English',
  language_ru: 'Русский',

  kind_spriteArchive: 'архив спрайтов (H3sprite.lod)',
  kind_dataArchive: 'архив данных (H3bitmap.lod)',
  kind_hotaArchive: 'архив HotA (HotA.lod)',
  kind_map: 'карта (.h3m)',
  kind_unknown: 'неизвестный файл',

  placeholder_title: APP_NAME,
  placeholder_missing: 'Выберите в настройках обоев: {files}.',
  placeholder_hint: 'Файлы берутся из вашей установки Heroes of Might and Magic III Complete и не покидают этот компьютер.',
  msg_LOADING: 'Загрузка {file}…',
  msg_FILE_MISSING: 'Файл {file} не найден. Выберите его заново.',
  msg_FILE_UNREADABLE: 'Не удалось прочитать {file}: {detail}',
  msg_WRONG_KIND: '{file} — это {found}, а не {expected}.',
  msg_UNKNOWN_FILE: '{file} не является архивом или картой Heroes III.',
  msg_UNSUPPORTED_MAP: '{file}: карты {format} пока не поддерживаются.',
  msg_CORRUPT_FILE: 'Файл {file} повреждён или не поддерживается: {detail}',
  msg_DATA_ARCHIVE_MISSING: 'Объекты скрыты: выберите архив данных (H3bitmap.lod).',
  msg_WEBGL_UNAVAILABLE: 'Эта система не может нарисовать карту: WebGL недоступен.',
  msg_CONTEXT_LOST: 'Графика была сброшена, карта скоро появится снова.',
  msg_CACHE_UNAVAILABLE: 'Локальный кэш недоступен, поэтому при каждом запуске файлы декодируются заново.',
  msg_FOLDER_EMPTY: 'В {file} не найдено карт (.h3m).',
  msg_FOLDER_FILTERED: 'Ни одна карта в {file} не подходит под фильтры ({detail}).',
  msg_FOLDER_UNREADABLE: 'Ни одну карту из {file} не удалось показать: {detail}',
  msg_FOLDER_NEEDS_ZIP: 'Эта программа обоев не умеет читать папку ({file}): заархивируйте карты в один файл и укажите .zip в «Папке с картами».',

  panel_title: APP_NAME,
  panel_files: 'Файлы',
  panel_choose: 'Выбрать файлы…',
  panel_drop: 'или перетащите архивы и карту в любое место страницы (для карты HotA — ещё HotA.lod)',
  panel_forget: 'Забыть файлы',
  panel_forget_done: 'Файлы и кэш удалены из этого браузера.',
  panel_help: 'Где взять файлы?',
  panel_keys: 'Стрелки или перетаскивание: прокрутка · U: уровень · R: новое случайное место · N: следующая карта · O: объекты · H: скрыть панель',
  panel_hide: 'Скрыть панель',
  panel_none: 'не выбран',
  panel_choose_folder: 'Выбрать папку…',
  panel_choose_zip: 'Выбрать .zip…',
  panel_folder_summary: '{file}: карт — {detail}',
  panel_current_map: 'Сейчас: {file}',
  panel_drop_folder: 'Перетащите папку с картами или .zip с картами на страницу либо выберите папку кнопкой.',

  package_title: APP_NAME,
  package_description: 'Анимированная карта приключений Heroes of Might and Magic III (Герои 3, HoMM3) из ваших файлов игры — издания Complete, а для карт Horn of the Abyss (HotA) ещё и HotA: местность, объекты, герои и города, как в оригинальной игре. Фанатский проект, не связан с издателями игры. Игровые файлы не входят в комплект.',
  help_files: 'Возьмите H3sprite.lod и H3bitmap.lod из папки Data вашей установки Heroes III Complete и любую карту (.h3m) из папки Maps. Поддерживаются карты Restoration of Erathia, Armageddon\'s Blade, Shadow of Death и Horn of the Abyss. Для карты HotA выберите ещё HotA.lod из папки Data вашей установки HotA — без него у карты HotA не будет её земель и объектов.',
  help_privacy: 'Файлы остаются на этом компьютере: они читаются локально и никуда не загружаются.',
  help_web: 'Выберите файлы кнопкой или перетащите их на страницу. Браузер запомнит их, пока вы не нажмёте «Забыть файлы».',
  help_wallpaper_engine: 'Wallpaper Engine разрешает обоям читать файлы только внутри их собственной папки, поэтому файлы нужно положить туда самостоятельно — без этого обои работать не будут. Скопируйте H3sprite.lod и H3bitmap.lod (из папки Data вашей установки Heroes III Complete) и карту (.h3m) в папку обоев, рядом с index.html; для этого предназначена подпапка «game». Настройки «Архив спрайтов» и «Архив данных» по умолчанию содержат game\\H3sprite.lod и game\\h3bitmap.lod, так что при стандартных именах остаётся вписать только карту (например game\\Arrogance.h3m); другие имена вводятся так же. Для карты HotA туда же нужно скопировать HotA.lod и вписать его в настройку «Архив HotA» (например game\\HotA.lod). Для источника «Папка с картами» Wallpaper Engine не умеет показывать список папки: заархивируйте карты в один файл (например game\\maps.zip, значение по умолчанию) и укажите его в «Папке с картами».',
  notice_wallpaper_engine: '<b><i><u>Важно:</u></i></b> обои могут читать файлы только внутри своей папки, поэтому скопируйте H3sprite.lod, H3bitmap.lod и карту (.h3m) в папку обоев самостоятельно (рядом с index.html; подойдёт подпапка «game») — иначе обои не загрузятся. Настройки архивов ниже уже указывают на game\\H3sprite.lod и game\\h3bitmap.lod; карту впишите так же (game\\ВашаКарта.h3m).<br></br>',
  spacer_wallpaper_engine: '<br></br>',
  help_lively: 'Откройте «Настроить» для обоев в Lively и нажмите «Обзор» в настройках файлов; Lively скопирует файлы в папку обоев. Архив HotA нужен только для карт HotA.',
  help_kde: `Установите плагин, откройте «Настроить рабочий стол и обои», выберите «${APP_NAME}» и укажите файлы. Архив HotA нужен только для карт HotA.`,

  store_links: 'Исходный код, README и файлы для всех платформ: [GitHub]({repository}) · [релизы]({releases}) · [версия для браузера]({pages})',
  store_feedback: 'Предложения и сообщения об ошибках принимаются только в [GitHub Issues]({issues}); комментарии и отзывы на страницах магазинов не отслеживаются.',
  store_on_workshop: 'Есть и в [Steam Workshop]({workshop}) для Wallpaper Engine.',
  store_on_kde_store: 'Есть и в [KDE Store]({kde_store}) для KDE Plasma 6.',
  store_kde_requirements: 'Нужен Qt WebEngine для QML, магазин сам его не установит: Fedora — `qt6-qtwebengine`, Debian/Ubuntu — `qml6-module-qtwebengine`, Arch — `qt6-webengine`.',
  kde_webengine_missing: `Для ${APP_NAME} нужен Qt WebEngine для QML. Установите его и перезапустите Plasma (или войдите в систему заново): Fedora — qt6-qtwebengine; Debian/Ubuntu — qml6-module-qtwebengine; Arch — qt6-webengine.`,
  panel_version: 'Версия {version}',
  panel_report: 'Сообщить о проблеме',
}

export const STRINGS: Record<Language, Record<StringKey, string>> = { en, ru }

/** Russian for any `ru` tag, English otherwise. */
export function pickLanguage(tag: string | null | undefined): Language {
  return typeof tag === 'string' && /^ru(\b|[-_])/i.test(tag.trim()) ? 'ru' : 'en'
}

/** Text for a key with `{name}` placeholders filled. */
export function format(lang: Language, key: StringKey, params: Record<string, string> = {}): string {
  return STRINGS[lang][key].replace(/\{(\w+)\}/g, (m, name: string) => params[name] ?? m)
}
